from tkinter import *
import tkinter.font as font
from tkinter import filedialog
def upload():
    window.file=filedialog.askopenfilename()
    print(window.file)
def doctor_details():
    window1=Tk()
    window1.geometry('-0+80')
    window1.title("Doctor Details")
    f2=Frame(window1)
    f2.configure(background='#ff8484')
    L2=Label(f2,bg='#ff8484',text="Doctor's Details:",font=("Monaco",28))
    L2.pack(side='left')
    f2.pack(side=TOP,fill='x')
    f92=Frame(window1)
    f92.configure(bg='#ff8484')
    l14=Label(f92,text='+++++++++++++++++++++++++++++++++++++++++++++',bg='#ff8484').pack(side='left')
    f92.pack(fill='x')
    f2_1=Frame(window1)
    f2_1.configure(background='#ff8484')
    L2_1=Label(f2_1,bg='#ff8484',text="Doctor Name : {0}".format('Somisetty sai vasavi Harsha Vardhan Gupta'),font=("Ariel",24))
    L2_1.pack(side='left')
    f2_1.pack(side=TOP,fill='x')
    f2_2=Frame(window1,bg='#ff8484')
    l2_2=Label(f2_2,text="Department    : {0}".format('E.N.T'),font=("Ariel",24),bg='#ff8484')
    l2_2.pack(side='left')
    f2_2.pack(side=TOP,fill='x')
    f93=Frame(window1)
    f93.configure(bg='#ff8484')
    l15=Label(f93,text=' ',bg='#ff8484').pack(side='left')
    f93.pack(fill='x')
    window1.mainloop()
def first_window(Event):
    window.destroy()
global window
window=Tk()
window.wm_attributes('-fullscreen',True)
window.configure(background='#ff8484')
f_back=Frame(window,bg='#ff8484')
back_image=PhotoImage(file="Back_Arrow.png")
back_label=Label(f_back,image=back_image,bg='#ff8484')
back_label.pack(side='left')
back_label.bind('<Button-1>',first_window)
f_back.pack(fill='x')
f11=Frame(window)
f11.configure(bg='#ff8484')
l10=Label(f11,bg='#ff8484',font=("Monaco",24),text='Some more Good Deeds to be done,for those coming up!')
l10.pack(side='left')
l11=Label(f11,bg='#ff8484',font=("Ariel",24),text='    10')
l11.pack(side='left')
f11.pack(fill='x')
f3=Frame(window)
f3.configure(background='#ff8484')
L4=Label(f3,bg='#ff8484',text="Patient's Details:",font=("Monaco",28))
L4.pack(side='left')
L00=Label(f3,bg='#ff8484',text="    ")
L00.pack(side='right')
B4=Button(f3,text='Doctor Details',command=doctor_details,font=("Ariel",14))
B4.pack(side='right')
f3.pack(fill='x')
f4=Frame(window)
f4.configure(background='#ff8484')
L5=Label(f4,bg='#ff8484',text="Name: {0}".format(name),font=("Ariel",24))
L5.pack(side='left')
f4.pack(fill='x')
'''entry3=Entry(f4,borderwidth=3,width=38)
entry3.insert(END,name)
entry3.pack(side='left')
'''
f7=Frame(window)
f7.configure(bg='#ff8484')
L6=Label(f7,bg='#ff8484',text="Gender:  {0}".format(gender),font=("Ariel",24))
L6.pack(side='left')
'''entry0=Entry(f4,borderwidth=3,width=20)
entry0.insert(END,gender)
entry0.pack(side='left')
'''
f7.pack(fill='x')
f4_1=Frame(window)
f4_1.configure(bg='#ff8484')
pn_p=Label(f4_1,text="Phone Number:   {0}".format(pn),font=("Ariel",24),bg='#ff8484')
pn_p.pack(side='left')
f4_1.pack(fill='x')
f4_12=Frame(window)
f4_12.configure(bg='#ff8484')
'''pn_p_e=Entry(f4_1,borderwidth=3,width=22)
pn_p_e.pack(side='left')
pn_p_e.insert(0,p_no)
'''
p_a=Label(f4_12,text="Age:  {0}".format(age),font=("Ariel",24),bg='#ff8484')
p_a.pack(side='left')
f4_12.pack(fill='x')
f4_2=Frame(window)
f4_2.configure(bg='#ff8484')
pn_w=Label(f4_2,text="Weight:  {0}".format(weight),font=("Ariel",24),bg='#ff8484')
pn_w.pack(side='left')
'''pn_w_e=Entry(f4_2,borderwidth=3,width=20)
pn_w_e.pack(side='left')
pn_w_e.insert(0,weight)
'''
f4_2.pack(fill='x')
f5_w=Frame(window,bg='#ff8484')
L_w=Label(f5_w,bg='#ff8484').pack()
f5_w.pack(fill='x')
f5=Frame(window)
f5.configure(background='#ff8484')
x=open('tests.txt','r').read().split('\n')
L7=Label(f5,bg='#ff8484',text="Tests:",font=("Monaco",28))
L7.pack(side='left')
f5.pack(fill='x')
for i in x:
    if i!='':
        f6=Frame(window,background='#ff8484')
        dot=Label(f6,text='o',font=("Ariel",20),bg='#ff8484').pack(side='left')
        tests1=Label(f6,text=i,font=("Ariel",24),bg='#ff8484').pack(side='left')
        f6.pack(fill='x')
    #waste=Label(f6,text='',font=("Ariel",14),bg='#ff8484').pack(side='top')
#f6.pack(fill='x')
f9=Frame(window)
f9.configure(bg='#ff8484')
l12=Label(f9,text=' ',bg='#ff8484').pack(side='left')
f9.pack(fill='x')
f8=Frame(window)
f8.configure(bg='#ff8484') 
l_tp=Label(f8,text="                                                                                 ",bg='#ff8484').pack(side='left')
b1=Button(f8,text='Open Reports')
myFont = font.Font(family='Monaco', size=20)
b1['font']=myFont
b1.pack(side='left')
l_tp2=Label(f8,text="                                                            ",bg='#ff8484').pack(side='left')
b2=Button(f8,text='Upload Report',command=upload)
b2['font']=myFont
b2.pack(side='left')
f8.pack(fill='x')
window.mainloop()
